### ISSUE TITLE
Set up CI and semantic-release

### ISSUE THREAD

**Issue by patrickocoffeyo** [emulsify-ds/compound#10]
do it

**Comment by ModulesUnraveled** [comment]
@patrickocoffeyo I created this PR that sets up husky/lint-staged/commitlint. I figured that might help with this ticket too https://github.com/emulsify-ds/compound/pull/12

**Comment by ModulesUnraveled** [comment]
This was completed in https://github.com/emulsify-ds/compound/pull/17
