### ISSUE TITLE
[BUG] Installing Compound via the Emulsify CLI results in missing .scss files from the component structure.

### ISSUE THREAD

**Issue by jimz0r** [emulsify-ds/compound#115]
**Describe the bug**
Installing Compound via the Emulisyf CLI (either by name or --repository --checkout options), results in missing .scss files found in the components folder. This results in a failed build/develop process due to missing index and component files (e.g `/components/00-base/base.scss` or `components/00-base/04-spacing`).

![image](https://github.com/emulsify-ds/compound/assets/7566786/cac25b60-23ad-4c6e-bcff-b30ac0b60d37)

This is likely due to the outdated [system.emulsify.json](https://github.com/emulsify-ds/compound/blob/main/system.emulsify.json) found in the project root. New .scss index files and changes to structure need to be added/updated.

**To Reproduce**
1. Use `emulsify init "MY_THEME"` within a Drupal project to intirialize Emuslify theme build.
2. Navigate to "MY_THEME"
3. Use `emulsify system install compound` or `emulsify system install --repository https://github.com/emulsify-ds/compound.git --checkout 2.0.0` to install the Compond system.
4. Run `npm install`
5. Run `npm run develop` or `npm run build`.

**Expected behavior**
After installing Compound via the Emuslify CLI, all files included in the repository should be present within the `components` stucture. This should result in a successful build/develop process.

**Desktop**
 - OS: Ubuntu 22.04.4 LTS via Windows 11 WSL 2.0

**Comment by karldivad** [comment]
I couldn't even install it, using Node 20.13.0.

Case 1:
* Command: `emulsify system install compound`
* Error: The system you attempted to install (compound) is invalid, as it does not contain a valid configuration file.
* Folder it creates: `.emulsify/cache/systems/3413609028970bcf92addcb6ca03f1f2`
* **After debugging**, it was looking for another folder name for some reason.

Case 2:
* Command: `emulsify system install --repository https://github.com/emulsify-ds/compound.git --checkout 2.0.1`
* Error: Unable to install system assets and/or required components: Error: ENOENT: no such file or directory, lstat '/Users/userName/.emulsify/cache/systems/34f2b669308d477ac9688a3c9b07daed/compound/components/00-base/01-colors'
* Folder it creates: `.emulsify/cache/systems/6e805b7c37e8565b3ddd400cf5040c6d`
* **After debugging**, it was looking for another folder name for some reason.

**Comment by franxo** [comment]
Hi,
Same issue as @karldivad mentioned

**Comment by jimz0r** [comment]
@karldivad confirmed, getting the same issue.

**Comment by bariman** [comment]
getting the same issue as @karldivad , using Node 20.14.0. @callinmullaney do you have any updates on the issue?

**Comment by maheshpih** [comment]
Hi there, facing the same issue as @bariman ... 
❯ emulsify system install --repository https://github.com/emulsify-ds/compound.git --checkout 1.18.0

ERROR Unable to install system assets and/or required components: Error: ENOENT: no such file or directory, lstat '/Users/username/.emulsify/cache/systems/ba74aaaabd9722679f9a856e78fc9f80/compound/components/00-base/01-colors'

**Comment by MinhInBlack** [comment]
I am too currently experiencing this issue. It keeps looking into the incorrect folder when its generating a different folder. Has anyone found a fix yet?

**Comment by calebtr-metro** [comment]
I believe the hash mismatch noted by [karldivad](https://github.com/karldivad) means that this likely an issue with emulsify-cli, not with compound.

**Comment by webcultist** [comment]
"The system you attempted to install (compound) is invalid, as it does not contain a valid configuration file." - everything freshly installed, I get the same error.

**Comment by callinmullaney** [comment]
Hello everyone. Apologies for the delay. I have a coworker looking into this as it does appear to be sourced from the CLI and not compound. We are comparing the CLI's expected system schema (https://github.com/emulsify-ds/emulsify-cli/blob/develop/src/schemas/system.json) with Compound's `system.emulsify.json` using a json validator (https://www.jsonschemavalidator.net/) - As to be expected there is the following error with the CLI's schema 
`Error when resolving schema reference 'variant.json#/definitions/platform'. Path 'properties.variants.items.anyOf[0].properties.platform', line 49, position 27.`

**Comment by deepsimran77** [comment]
I am getting the same error while installing the 'compound' system that configuration file is invalid.

**Comment by sryanb** [comment]
Same issue. This can be worked around by manually installing Compound (download the compound zip, copy files/folders into theme).

**Comment by dchaffin** [comment]
@sryanb Do I drag EVERYTHING from the compound directory or just the assets, components, config and templates directories? Thanks!

**Comment by callinmullaney** [comment]
Hello everyone! Thanks for you patience with this issue. It's been a frustrating bug to track down and resolve but we were able to issue a new release for Emulsify CLI (v1.11.3) the resolves it. Use `npm install -g @emulsify/cli` to update and verify with `emulsify -V`.

In addition to the CLI's expected schema not being correct (see my comment above) we found that release tags for Compound and Emulsify UI Kit were not being passed. This caused the CLI to get to a json validation step without even being able to checkout the system's git repository. At any rate, please update your local install. Happy coding!
