### ISSUE TITLE
[BUG] Logo component not defined in twig

### ISSUE THREAD

**Issue by codechefmarc** [emulsify-ds/compound#90]
**Describe the bug**
After installing compound with `--all` components, an error shows up in Drupal watchdog:

```
Twig\Error\LoaderError: Template "@molecules/logo/logo.twig" is not defined in "@organisms/site/site-header/_site-header-branding.twig" at line 1. in Twig\Loader\ChainLoader->getCacheKey() (line 99 of /app/vendor/twig/twig/src/Loader/ChainLoader.php).
```

**To Reproduce**
1. Spin up a new Emulsify theme from the project root: `emulsify init "My New Theme"`
2. Go to the newly created theme directory and run `emulsify system install compound --all` to install all components from compound.
3. Enable the new theme in Drupal
4. Flush Drupal cache
5. Attempt to view a page on the site, this caused a "The website encountered an unexpected error. Please try again later." error for me.
6. Visit `/admin/reports/dblog` and verify that the error is as stated above.

**Expected behavior**
The logo component doesn't appear to be loading into the system from the compound install. It should be installed with the `--all` flag.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Browser Chrome
 - Version 111.0.5563.64 (Official Build) (arm64)

**Additional context**
Possibly related to: https://github.com/emulsify-ds/compound/releases/tag/1.13.1

**Comment by lpeabody** [comment]
I'm also seeing this. I also tried installing via the git repo and branch method `emulsify system install --repository=git@github.com:emulsify-ds/compound.git --checkout=main`. The result installed component files looks like this:

![image](https://user-images.githubusercontent.com/419534/230244374-35f1c2ec-6f4a-43f4-b84c-52344209c36c.png)

**Comment by lpeabody** [comment]
It also results in:

```
Twig\Error\LoaderError: Template "@molecules/tabs/tabs.twig" is not defined in "themes/custom/page_demo_theme/templates/navigation/menu-local-tasks.html.twig" at line 14. in Twig\Loader\ChainLoader->getCacheKey() (line 98 of /var/www/html/vendor/twig/twig/src/Loader/ChainLoader.php).
```
